import mobilisslide1 from "../../../assets/images/mobilis4manufacturingslideimage1.jpg";
import mobilisslide2 from "../../../assets/images/mobilis4manufacturingslideimage2.jpg";
import mobilisslide3 from "../../../assets/images/mobilis4manufacturingslideimage3.jpg";
import mobilisslide4 from "../../../assets/images/mobilis4manufacturingslideimage4.jpg";
import mobilisslide5 from "../../../assets/images/mobilis4manufacturingslideimage5.jpg";
import mobilisslide6 from "../../../assets/images/mobilis4manufacturingslideimage6.jpg";
import mobilisslide7 from "../../../assets/images/mobilis4manufacturingslideimage7.jpg";

export const slides = [
  { img: mobilisslide1, title: "3D SCANNING", desc: "3D scanning supports highly accurate and individual measurements of our patients. The optical scanner enables us to electronically capture a high-resolution 3D model of our patient in seconds – without any patient contact or the mess and discomfort of plaster. After saving the files, the designer at MOBILIS can immediately start the workflow." },
  { img: mobilisslide2, title: "CAD (Computer Aided Design) RECIFICATION", desc: "Powerful software tools are used to design any type and complexity of body parts to an accurate digital model. The software allows our Orthotic and Prosthetic designer to implement knowledge and expertise to a device design like never before and realize complex design approaches in the most efficient manner. It increases the accuracy of the fit and ensures best function in the device." },
  { img: mobilisslide3, title: "EDP (Electronic Data Process) in Manufacturing", desc: "MOBILIS uses automated methods to process manufacturing and patient data. This makes the repetitive activities needed to process large volumes patient information, a relatively simple task. This ensures an error free and fast production. Our clinician can access the data from any satellite locations and give instructions to the production staff. Single route production will ensure perfect finishing" },
  { img: mobilisslide4, title: "CLOUD COMPUTING", desc: "Cloud computing allows us to access, store, manage, and process data from different locations. This helps us progress rapidly with minimal management effort. We achieve the highest data safety while maintaining the best security measures. The manufacturing process can be supervised from any location enabling us to generate and analyse valuable manufacturing data to continuously improve the output quality of our products." },
  { img: mobilisslide5, title: "CAM / ROBOTIC SUPPORTED MANUFACTURING", desc: "Our 7-axis robotic milling system is the fastest and most versatile carving solution which allows us to create large varieties of model types for the production of orthotics, prosthetics and custom moulded seats. The robot is very precise and is able to carve any material. With the automated feeding line, our system works 24/7, is remotely controllable and supervised to save time and provide faster delivery." },
  { img: mobilisslide6, title: "ELECTRONIC LINE ASSEMBLY", desc: "All our product designs and assembly instructions are delivered through the Electronic Line Assembly Management System (ELAM), which guides and instructs our production staff through the whole manufacturing process. Visual support of complex steps and material selection ensures an efficient production with 0% error probability. The system ensures a stable process for best quality while increasing efficiency and staff satisfaction." },
  { img: mobilisslide7, title: "3D PRINTING", desc: "3D printing is an amazing technology that has opened the doors for the future prosthetic and orthotic industry. 3D printing is unlikely to replace many traditional manufacturing methods, yet there are many applications where a 3D printer is able to deliver a design quickly and with high accuracy from a functional material. One of the biggest concerns for us is, how to manufacture a device as efficiently as possible. Most devices require a large number of manufacturing steps to be produced by traditional technologies." }
];
